### ISSUE TITLE
Tab size

### ISSUE THREAD

**Issue by S-Borkowski** [gildas-lormeau/JSONVue#99]
CSS tab-size doesn't seem to work neither for body or pre. Can you tell me how can I customize this?

**Comment by gildas-lormeau** [comment]
Open the style editor via the options page of JSONVue (or open chrome-extension://chklaanhfefbnpoihckbnefhakgolnmc/css-editor.html) and adjust the value of `margin-left` in the `.collapsible` rule.

**Comment by S-Borkowski** [comment]
awesome, that worked :D do you know how can i add border-left so its easier to see where collapsible starts and ends? I know how to do it but without an offset (and i really want it to start where my collapser-after char is)

**Comment by gildas-lormeau** [comment]
You'll get it if you reset the stylesheet by clicking on the "reset" button at the top right of the style editor. Otherwise, add or replace the content of:
```css
.collapsible .collapsible::before {
   [...]
}
```

with:
```css
.collapsible .collapsible::before {
  border-width: 0;
  border-left: #d3d3d3 .1em dashed;
  content: " ";
  max-width: .1em;
  position: absolute;
  height: calc(100% - 3.4em);
  left: .4em;
  top: 1.8em;
}
```
